[build]
  base = "client"
  publish = "dist"
  command = "npm run build"

# Forward API requests to Render backend
[[redirects]]
  from = "/api/*"
  to = "https://inventory-prj.onrender.com/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
